name,model,choice
jLabelS,jTextField1,
jLabelI,longField1,
jLabelCombo,jComboBox1,
jLabelDS,jTextField3,
jLabelDL,jTextField4,
jCheckBox2,jCheckBox1,
jRadioButton2,jRadioButton1,test2
jRadioButton3,jRadioButton1,test3
jTextFieldRadio,jRadioButton1,
