/*
 * VdrSelectDialog.java
 *
 * Created on 2007/03/12, 20:46
 */

package org.seasar.golf.uexample.frame;

import java.util.HashMap;
import org.seasar.golf.GolfDialog;
import org.seasar.golf.form.FormManager;

/**
 *
 * @author  shimura
 */
public class DialogTemplate extends javax.swing.JDialog implements GolfDialog {
    
    /** Creates new form VdrSelectDialog */
    public DialogTemplate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private FormManager formManager = null;
 //   private GolfTableModel golfTableModel= new GolfTableModel();        
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VdrSelectDialog dialog = new VdrSelectDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    public FormManager getFormManager() {
        return formManager;
    }

    public void setFormManger(FormManager formManager) {
        this.formManager = formManager;
    }

    public void initBinding(HashMap params) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void processAction(HashMap params) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
